spring:
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
    listener:
      simple:
        default-requeue-rejected: false
rabbitmq:
  store-product:
    queue: store-product.q
connectors:
  model:
    url: 
  catalog:
    url: 