server:
  port: 8130

feign:
  client:
    config:
      ModelConnector:
        loggerLevel: full
      CatalogConnector:
        loggerLevel: full

connectors:
  model:
    url: localhost:8110
  catalog:
    url: localhost:8100

logging:
  level:
    com:
      malpro:
        processor: DEBUG